### ISSUE TITLE
model training

### ISSUE THREAD

**Issue by chenjiahao0124** [THU-VCLab/HGGD#1]
Hello, I have reviewed your paper and code, and I feel that you have done a great job. Could you please share your training code? I would like to see the details of your model training. Thank you.

**Comment by ChenThree** [comment]
Thank you for your interest! We will release our training code soon, may be in the next 2 weeks.

**Comment by chenjiahao0124** [comment]
> 感谢您的关注！我们将很快发布我们的训练代码，可能在未来 2 周内发布。

Thank you very much, I will be patient and wait.

**Comment by ChenThree** [comment]
Training code and guide have been released.
