### ISSUE TITLE
question about the dataset

### ISSUE THREAD

**Issue by Xiong5Heng** [THU-VCLab/HGGD#10]
Hello, 
Thanks for your work. 
I downloaded the dataset from the link https://cloud.tsinghua.edu.cn/d/e3edfc2c8b114513b7eb/, and there are **189 scenes** in this zip file. However, I notice in your paper that you mention that training requires **500 scenes**. 
My question is whether the final performance of the model trained using a data set of only 189 scenes can reach the value in the paper?

**Comment by ChenThree** [comment]
Thank you for your interst! We conduct 2 series of experiments in our paper. One is on Acronym dataset with your mentioned 500 scenes. Then the other one is on the GraspNet-1B dataset which is the 190 (0~189, 100 fo training and 90 for testing) scenes you downloaded.
