### ISSUE TITLE
Only grasping pose detection on the edge of the scene

### ISSUE THREAD

**Issue by normajeane-m** [THU-VCLab/HGGD#11]
![Screenshot from 2024-05-07 16-24-08](https://github.com/THU-VCLab/HGGD/assets/40226545/742af207-7187-4dcc-8548-4c677ceaa1f6)

Hello, HGGD researchers,

Firstly, I'd like to express my gratitude for providing excellent research and a user-friendly implementation.

When I tried detecting grasping pose in my environment using the provided demo, I encountered an issue where the poses were being detected on the outer edges as shown in Figure. 
I would appreciate any feedback on this matter.

Thank you.

**Comment by ChenThree** [comment]
Thanks for your interest in our work! Can you please visualize the detected heatmap? Or you can try running with more region centers (center_num), maybe 128 or 256?

**Comment by ChenThree** [comment]
Closed for no more comments.
