### ISSUE TITLE
Regarding your new article: Rethinking 6-Dof Grasp Detection: A Flexible Framework for High-Quality Grasping

### ISSUE THREAD

**Issue by huamo555** [THU-VCLab/HGGD#12]
Hello author,
 I recently read your latest article: Rethinking 6-Dof Grasp Detection: A Flexible Framework for High-Quality Grasping，I have some questions about why the GS results reproduced in the two papers change, did you turn on collision detection processing in the tests when you ran the tests in the new paper?Will you open source the code for your latest paper?
I would be grateful for your reply !

**Comment by ChenThree** [comment]
Thank you for your interest in our work and careful reading. Yes, actually there are two results for each method, that it with/without collision detection and there are two versions of our HGGD paper. One is the newer one on the arXiv, in which we show the GS results without collision detection and in the RA-L version on IEEE Xplore in which we show GS results with collision detection. We will consider updating the arXiv version for a more clear comparision.

**Comment by huamo555** [comment]
> Thank you for your interest in our work and careful reading. Yes, actually there are two results for each method, that it with/without collision detection and there are two versions of our HGGD paper. One is the newer one on the arXiv, in which we show the GS results without collision detection and in the RA-L version on IEEE Xplore in which we show GS results with collision detection. We will consider updating the arXiv version for a more clear comparision.

Thank you for your response and I look forward to publishing and open-sourcing your new paper.

**Comment by Robust-Depth** [comment]
> Thank you for your interest in our work and careful reading. Yes, actually there are two results for each method, that it with/without collision detection and there are two versions of our HGGD paper. One is the newer one on the arXiv, in which we show the GS results without collision detection and in the RA-L version on IEEE Xplore in which we show GS results with collision detection. We will consider updating the arXiv version for a more clear comparision.

Hello, and thank you for your work. After reading this comment, which states that the RA-L version uses collision detection, it seems that the results in the RA-L paper are worse than those in both the new and old arXiv papers. Does this mean you found that collision detection led to worse performance?
