### ISSUE TITLE
在运行test_graspnet.py时遇到了问题

### ISSUE THREAD

**Issue by RecardoM** [THU-VCLab/HGGD#13]
在您的代码中test_graspnet.py分为了两个函数：def inference（）和def evaluate()
在log中，我看到了inference函数得到的info：
{**test_graspnet.py:140} INFO - Using saved anchors
{test_graspnet.py:382} INFO - Time stats:
{test_graspnet.py:383} INFO - Total: 34.181 ms
{test_graspnet.py:386} INFO - 2d: 7.364 ms  data: 16.780 ms  6d: 5.255 ms  colli:2.982 ms  nms: 1.802 ms**
但是并没有得到evaluate中的info： 
   **logging.info(f'Scene: {args.scene_l} ~ {args.scene_r}')
    logging.info(f'colli == {colli}')
    logging.info(f'ap == {ap}')
    logging.info(f'ap0.8 == {aps[3]}')
    logging.info(f'ap0.4 == {aps[1]}')** 
这些信息在log里都没有。
同时，test过程在scene 100-130之间，会卡在
**score list == [ 0.2  0.4  0.4  0.4  0.2 -1.   0.6  0.2 -1.   0.2  0.2 -1.   0.4  0.2 0.4 -1.   0.6  0.2  0.2 -1.   0.4 -1.   0.4  0.4 -1.   0.4  0.2  0.4 0.4  0.4  0.6  0.2  0.4 -1. ]
colli == 0.23529411764705882
Mean Accuracy for scene:0128 ann:0255 = 66.559**  这里，然后就不动了。
我尝试把100-130换到130-160
结果也会卡住，在scene:0158 ann:0255时卡住
我不知道问题出在哪里了，为什么会这样内😎

**Comment by RecardoM** [comment]
![问题截图](https://github.com/THU-VCLab/HGGD/assets/162848763/36722e75-8c46-4198-a645-fff2d1213c28)
test就截止到这里，接着就不往下继续运行了

**Comment by ChenThree** [comment]
感谢你对我们工作的兴趣！这个可能是因为多线程 graspnet 测试的一点 bug，我们之前也遇到过，可能与机器的内存大小有关，你可以把 worker 数量调小一点试试看（<=4）？

**Comment by RecardoM** [comment]
> 感谢你对我们工作的兴趣！这个可能是因为多线程 graspnet 测试的一点 bug，我们之前也遇到过，可能与机器的内存大小有关，你可以把 worker 数量调小一点试试看（<=4）？

今天分别试了把worker调为2和1 都会卡住 还有其他可以尝试的解决办法嘛

**Comment by ChenThree** [comment]
这样子的话可以尝试直接单线程用 apply 而非 apply_async 试试
