### ISSUE TITLE
How to get the TS-ACRONYM dataset you used in the paper?

### ISSUE THREAD

**Issue by rcao-hk** [THU-VCLab/HGGD#14]
Hi,

Thank you for your work. I just wondering how to get the TS-ACRONYM you generated. Is there any release plan for it?

Best regards,
Rui

**Comment by ChenThree** [comment]
Thank you for your interest! We generate the dataset using object and labels from Acronym dataset with pyrenderer. The dataset and codes may be released in future but are not the priority of our project now.

**Comment by rcao-hk** [comment]
Hi,

Thank you for your reply. I noticed you generated dense labels for scenes of TS-ACRONYM, which means you followed the label method used in GraspNet right?

Best,

**Comment by ChenThree** [comment]
> Hi,
> 
> Thank you for your reply. I noticed you generated dense labels for scenes of TS-ACRONYM, which means you followed the label method used in GraspNet right?
> 
> Best,

We use the labels from Acronym dataset (1k labels per object) to generate scene-level labels via transformation and collision check.
