### ISSUE TITLE
Generate preprocessed grasp poses

### ISSUE THREAD

**Issue by paolotron** [THU-VCLab/HGGD#17]
Hi I've seen that you use a different set of grasp labels that you generate from the original graspnet1billion dataset, you provide the link but I didn't find how you originally generated them, could you tell me how to generate them from scratch?

**Comment by ChenThree** [comment]
Thanks for your interest in our work. You can also check [issue3](https://github.com/THU-VCLab/HGGD/issues/3).

> Our data generation pipeline mainly follows the 6-Dof grasp to rect grasp conversion provided in the graspnet dataset api, while the difference is that we save the grasp rotation as Euler angels in the rect grasp class. There may not be an exact schedule for the code release for grasp generation, because it requires extra code reorganization and testing, but if there is any progress in the release of this part, we will update in this repo.
