### ISSUE TITLE
如何应用到UR3e上

### ISSUE THREAD

**Issue by LemonQC** [THU-VCLab/HGGD#18]
您好，请问如何将预测的结果应用到ur3e上，能否提供一些参考。

**Comment by ChenThree** [comment]
你好！我们的算法提供了相机坐标系下的抓取位姿，在部署到真机的时候可以结合相机在世界坐标系下的位姿进行位姿转换到机械臂的坐标系，然后再进行路径规划并控制机械臂进行抓取

**Comment by LemonQC** [comment]
能否提供一份你们使用的参考一下呢，谢谢

**Comment by ChenThree** [comment]
位姿计算机、械臂的控制和操作代码可以参考 ros 相关代码和包来实现，不同的平台的实现也可能不同，真机代码不属于我们目前仓库打算包括的代码范畴

**Comment by LemonQC** [comment]
那好吧，谢谢
