### ISSUE TITLE
Some objects not detected

### ISSUE THREAD

**Issue by lishiyu005** [THU-VCLab/HGGD#2]
Dear authors,

Thanks for your great work. This code has significant improvement compared with Graspnet-1billion. However, I am confused why some object is not detected. For example, scissor in the demo is not detected for grasping. Is this due to scissor is not in the training dataset? How can I fix this issue?
![Screenshot from 2024-02-24 17-09-30](https://github.com/THU-VCLab/HGGD/assets/118447498/8e352df4-424d-4e73-a31c-e770fd12b03f)

Thank you very much.

Best regards,
Shiyu Li

**Comment by ChenThree** [comment]
Thanks for your interest in our work! You can try running with more region centers (center_num), maybe 128 or 256

**Comment by lishiyu005** [comment]
![Screenshot from 2024-02-24 21-44-17](https://github.com/THU-VCLab/HGGD/assets/118447498/7a3ff0b5-4691-40cd-9a59-8b8c5b99fc48)
I changed it to 256, but the scissor is still not detected.

**Comment by ChenThree** [comment]
You can visualize the predicted heatmap. Maybe the predicted value on the scissors is relatively lower.

**Comment by ChenThree** [comment]
Closed for no more comments.
