### ISSUE TITLE
Access token for Tsinghua Cloud

### ISSUE THREAD

**Issue by aditya-sapienrobotics** [THU-VCLab/HGGD#20]
Hi,

Thank you for your work. Is the Tsinghua Cloud realsense checkpoint available publicly as I am unable to download it, says invalid access token.

Best regards,
Aditya Patil

**Comment by ChenThree** [comment]
I check the link and I can download the checkpoint without problem. Is there any network issue with you?

**Comment by aditya-sapienrobotics** [comment]
[Screencast from 10-03-2024 08:43:13 PM.webm](https://github.com/user-attachments/assets/95e230a3-41ff-4cbf-865a-2fa5f9a7aa48)
Attaching the video for reference.

**Comment by ChenThree** [comment]
I've reupload the ckpts and data to google cloud, maybe try with this link?
[google drive](https://drive.google.com/drive/folders/1IV9gmD4u67KjhciJob4Y0Bc7JBY4kF0K?usp=sharing)

**Comment by aditya-sapienrobotics** [comment]
Thanks Chen, this drive link worked for me, was able to download ckpts and data as well.

Best regards,
Aditya Patil
