### ISSUE TITLE
Pick a certain object

### ISSUE THREAD

**Issue by percypeng5221** [THU-VCLab/HGGD#21]
Hi,

Great work! Very useful. I'm wondering whether there are clever ways to specify that I only want to pick 1 certain object among all the objects? Thanks!

Best,
Percy

**Comment by percypeng5221** [comment]
Cool! Thanks for the quick reply! One questions, if we apply such a mask, it's equivalent to that the algorithm only sees 1 object, right? Then would the grasp point generation not considering obstacle avoidence, like generating grasp points that's not feasiable?

**Comment by ChenThree** [comment]
If the mask is applied on the predicted heatmap (output by the heatmap model, already containing the obstacle avoidence information), it will only affect the center sampling process on the heatmap.

**Comment by percypeng5221** [comment]
Got it! Thank you. Very helpful!
