### ISSUE TITLE
Generality of the model

### ISSUE THREAD

**Issue by menggui1993** [THU-VCLab/HGGD#22]
Hi, thanks for your work. I have some questions about the generality of the model.

You have provided two checkpoints for the two cameras. Is the model related to the camera type? e.g. are the camera intrinsics encoded into the model?

**Comment by ChenThree** [comment]
Thanks for your interest in our work. For a fair comparision, we train two model (realsense/kinect) on the two parts of the dataset. Thus, the model performance may be related to the camera type. However, it's easy to conduct hybrid training on the two dataset.
