### ISSUE TITLE
Unable to recognize some objects

### ISSUE THREAD

**Issue by RESHINE-HIT** [THU-VCLab/HGGD#23]
The model cannot recognize some specific objects, such as the scissors in the demo. Do you think this is a problem with the dataset or the model?

**Comment by ChenThree** [comment]
Thanks for your interest in our work! You can refer to [issue#2](https://github.com/THU-VCLab/HGGD/issues/2)

**Comment by RESHINE-HIT** [comment]
![image](https://github.com/user-attachments/assets/3113be53-e5c3-4177-92b5-9f7569b76009)
Thank you for your wonderful work! Indeed, the heatmap shows no heatmap of scissors. So the model did not learn the characteristics of scissors, and I guess the reason is that the depth map of scissors is not obvious?

**Comment by ChenThree** [comment]
Yes, it may be because the depth map of scissors is not obvious and the other objects is more graspable than the scissors, which may orignate from the heatmap training set generation (rather than using all the grasp labels, we only preserve the grasp with high force-closure scores).
