### ISSUE TITLE
Inquiry on Real-Time Grasp Prediction Methodology

### ISSUE THREAD

**Issue by Ryze-jo** [THU-VCLab/HGGD#4]
I recently came across your work, and I must commend you on the groundbreaking results and the innovative approach your team has adopted. The videos showcasing real-time grasp prediction were particularly inspiring.

Would you be willing to share more insights or any advice on replicating such real-time grasp prediction capabilities?

**Comment by ChenThree** [comment]
Thanks for your interest! We make the video by simply deploying our method with a realsense d435i camera. The grasp detection process is the same as that in the [demo](./demo.py).
