### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: './realsense_checkpoint'

### ISSUE THREAD

**Issue by RecardoM** [THU-VCLab/HGGD#5]
When I try to "bash test_graspnet.sh", reported this error "IsADirectoryError: [Errno 21] Is a directory: './realsense_checkpoint'"
It seems like it needs a specific file instead of a directory.
How can I solve this problem？
Sincerely thank you for your help

**Comment by RecardoM** [comment]
I have downloaded your checkpoint and setted the path to be the same as yours.

**Comment by RecardoM** [comment]
It confused me for a long time. How should I set THE "--checkpoint" PATH .
I haven't seen any ".pth" or ".pt" file in “realsense_checkpoint” .
Which specific file should this "checkpoint" path lead to?

**Comment by ChenThree** [comment]
The “realsense_checkpoint” is exactly our model checkpoint, because we save it without an extension like “.pth”. It should not be a directory but a file.

**Comment by RecardoM** [comment]
> The “realsense_checkpoint” is exactly our model checkpoint, because we save it without an extension like “.pth”. It should not be a directory but a file.

谢了兄弟，我知道我哪错了，我把checkpoint文件当成个压缩文件解压了，那肯定不对了，正常放着就没事，非常感谢非常感谢
