### ISSUE TITLE
Modifications to graspnetAPI in Your Repo

### ISSUE THREAD

**Issue by rcao-hk** [THU-VCLab/HGGD#7]
Hi,

I'm exploring the version of graspnetAPI in your repo for my project. Could you briefly outline the main changes you've made compared to the original version? Specifically interested in any new features or major alterations.

Thanks for your work and looking forward to your reply.

Best,
Rui

**Comment by ChenThree** [comment]
We mainly add the support of custom dataset split for both training and evaluation, which is not supported in the original graspnetAPI. Howerver, it seems that the newest API has included this feature (see: https://github.com/graspnet/graspnetAPI/commit/a2d688e16ddee474a07645641040b2f9f0d6c115). You can try the latest version of graspnetAPI.
