### ISSUE TITLE
Meaning of grasp labels

### ISSUE THREAD

**Issue by lishiyu0088** [THU-VCLab/HGGD#8]
Dear author,

I saw there are some grasp annotations in the label files. What is the meaning of translation_d, rotation_d and width_d?
{"numgrasp": 146, "translation_d": 6.7442166274596925e-09, "rotation_d": 5.012725293206674e-05, "width_d": 0.0028016255560493948}

Are they used in the training process?

Best regards,
Shiyu Li

**Comment by lishiyu0088** [comment]
I have another question regarding to the paper. In the paper, it is mentioned "d denotes the depth offset from the grasp center to corresponding point cloud surface point. Refer to appendices for more details of our data preparation".

However I cannot find any appendices to the paper. Can you explain how to calculate "center_z_depth" in the grasping labels? Thank you very much.

**Comment by ChenThree** [comment]
> Dear author,
> 
> I saw there are some grasp annotations in the label files. What is the meaning of translation_d, rotation_d and width_d? {"numgrasp": 146, "translation_d": 6.7442166274596925e-09, "rotation_d": 5.012725293206674e-05, "width_d": 0.0028016255560493948}
> 
> Are they used in the training process?
> 
> Best regards, Shiyu Li

Thank you for your interest of our work. These are some log files output during our grasp label processing scripts to check the validity of the processed labels. You can just ignore them.

**Comment by ChenThree** [comment]
> I have another question regarding to the paper. In the paper, it is mentioned "d denotes the depth offset from the grasp center to corresponding point cloud surface point. Refer to appendices for more details of our data preparation".
> 
> However I cannot find any appendices to the paper. Can you explain how to calculate "center_z_depth" in the grasping labels? Thank you very much.

You can refer to Fig. 2 in our paper to get how to get the z offset. It's the distance of the grasp centers to the corresponding point in the pointcloud (oftenly the object surface) along z-axis.

**Comment by lishiyu0088** [comment]
Thank you very much
