### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by wu467** [THU-VCLab/HGGD#9]
您好！
首先十分感谢大佬能提供代码学习
我有些问题想问一下：

    如果我要用HGGD对新的物体进行抓取，可以直接用你提供的checkpoint吗？还是要构建自己的数据集并训练？
    请问您是如何构建自己的数据集的呢（比如制作工具）？

**Comment by Jinbo-Zuo** [comment]
I have a similar problem.
I want to deploy this work on my robot, but the gripper and camera angle direction of my robot are different from yours in the paper. I need to rebuild the dataset, so I want to know how to build the dataset.
Especially, my camera perspective is not at the top, which will result in poor quality of point cloud information and will lead to bad grasp-results if you use your dataset directly.

**Comment by Jinbo-Zuo** [comment]
Okay, I just saw in another issue that you said the dataset generation code will be released soon. Thank you for your contribution, and look forward to updates!

[https://github.com/THU-VCLab/HGGD/issues/3](url)

**Comment by ChenThree** [comment]
> 您好！ 首先十分感谢大佬能提供代码学习 我有些问题想问一下：
> 
> ```
> 如果我要用HGGD对新的物体进行抓取，可以直接用你提供的checkpoint吗？还是要构建自己的数据集并训练？
> 请问您是如何构建自己的数据集的呢（比如制作工具）？
> ```

你好！如果需要对对新的物体进行抓取可以直接用你提供的 checkpoint 去检测抓取，我们的工作与之前的 GSNet、GraspNet-baseline 都是不依赖于具体的物体模型的，理论上具有比较好的泛化能力
关于数据构建，我们基于 GraspNet 的原始标注做了一定的过滤和转换，目前我们这个工作的后续工作仍在进行，数据处理的代码可能会在未来随着我们方法的改进版本一起放出

**Comment by ChenThree** [comment]
> I have a similar problem. I want to deploy this work on my robot, but the gripper and camera angle direction of my robot are different from yours in the paper. I need to rebuild the dataset, so I want to know how to build the dataset. Especially, my camera perspective is not at the top, which will result in poor quality of point cloud information and will lead to bad grasp-results if you use your dataset directly.

Thank you for your interest of our work. Actually, GraspNet-1B dataset is captures from multiple camera angle directions, not only from the top. As for the gripper, every grasp is predicted with a specific width, which can be used for filtering or any post-processing to be adopted on different grippers. You can just try the pretrained checkpoint to check the prediction.
